# Generated by Django 3.0.8 on 2021-03-04 04:23

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('groupbill', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Report',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('comment', models.CharField(blank=True, max_length=255, null=True, verbose_name='Chú thích')),
                ('solution', models.CharField(blank=True, max_length=255, null=True, verbose_name='Hướng xử lí')),
                ('status', models.IntegerField(choices=[[1, 'N'], [2, 'P'], [3, 'E']], verbose_name='Trạng thái biên bản')),
                ('number_driver', models.CharField(blank=True, max_length=30, null=True, verbose_name='Biển số xe')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='Ngày tạo')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='Ngày cập nhật cuối')),
                ('group', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='groupbill.GroupBill')),
                ('user_create', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='RecordReport',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('bill_number', models.IntegerField(blank=True, null=True, verbose_name='Số hóa đơn')),
                ('sku', models.CharField(blank=True, max_length=50, null=True, verbose_name='Mã sản phẩm')),
                ('amount', models.CharField(blank=True, max_length=23, null=True, verbose_name='Số lượng')),
                ('unit', models.CharField(blank=True, max_length=20, null=True, verbose_name='Đoen giá')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='Ngày tạo')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='Ngày cập nhật cuối')),
                ('report', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='report.Report')),
            ],
        ),
    ]
